### ISSUE TITLE
Better LLM-models?

### ISSUE THREAD

**Issue by Yukkun** [Hukasx0/character-factory#11]
Would it be possible to use better language models with this? I would prefer using something that is 13B as they are far better than 7B ones.

**Comment by Hukasx0** [comment]
It is possible, I only inserted the ones on which I tested and under which I made prompts, but as llm in these scripts you can use any llm model.

You only replace these two lines:
```py
model_url = "link_to_llm_model"
```

```py
model="models/model_name"
```
The first line is at the top of every script, the second is inside llm variable:
```
llm = CTransformers(
        model="models/model_name",    # here
        model_type="llama",
        gpu_layers=gpu_layers,
        config={
            "max_new_tokens": 1024,
            "repetition_penalty": 1.1,
            "top_k": 40,
            "top_p": 0.95,
            "temperature": 0.8,
            "context_length": 8192,
            "gpu_layers": gpu_layers,
            "stop": [
                "/s",
                "</s>",
                "<s>",
                "<|system|>",
                "<|assistant|>",
                "<|user|>",
                "<|char|>",
            ],
        },
    )
```

**Comment by Hukasx0** [comment]
In every script available in the repository, I use the [CTransformers](https://github.com/marella/ctransformers) library for this. 
Here is the list of models listed as supported from their repository:
![supported_models](https://github.com/Hukasx0/character-factory/assets/82332291/9720cf96-012f-4d52-9dd6-86492f7b7404)
