### ISSUE TITLE
ModuleNotFoundError: No module named 'antlr4'

### ISSUE THREAD

**Issue by visteras** [Hukasx0/character-factory#3]
I just install pycharm and run:
1) `pip install -r requirements-cuda.txt`
2) `python ./app/main.py --topic "anime schoolgirl" --negative-prompt "hyperrealistic, realistic, photo"`

I see error with ModuleNotFoundError: No module named 'antlr4'

info:
```
pip --version
pip 23.3.1 from ...\AppData\Local\Programs\Python\Python310\lib\site-packages\pip (python 3.10)
```

```
python --version
Python 3.10.6
```
part of pip install log:
```
Installing collected packages: argparse, antlr4-python3-runtime
  Attempting uninstall: antlr4-python3-runtime
    Found existing installation: antlr4-python3-runtime 4.9
    Uninstalling antlr4-python3-runtime-4.9:
      Successfully uninstalled antlr4-python3-runtime-4.9
Successfully installed antlr4-python3-runtime-4.8 argparse-1.4.0
```

**Comment by Hukasx0** [comment]
I personally don't use PyCharm, so I don't know how to fix it, only I can make one suggestion,
**Try running the script in MiniConda**:

(If you have conda on your computer and know how to use it you can skip to point 3.)

## First launch in Conda
1. download miniconda from https://docs.conda.io/projects/miniconda/en/latest/
2. familiarize yourself with how conda works https://conda.io/projects/conda/en/latest/user-guide/getting-started.html
3. Clone git repository
```
git clone https://github.com/Hukasx0/character-factory
```

4. Open the anaconda prompt and enter the path of the folder, e.g., 
```
cd C:\Users\me\Desktop\character-factory
```

5. Execute these commands in the conda command prompt step by step.

```
conda create -n character-factory
```

```
conda activate character-factory
```

```
conda install python=3.11
```

```
pip install -r requirements-cuda.txt
```
if everything was correct you can start using the script

## Next launch in Conda
Later, the next time you run it, you don't need to create a new environment, just repeat step 4. and type in (in the conda command prompt)
```
conda activate character-factory
```
and you can use the script

**Comment by visteras** [comment]
TY! Its work! 
Buuut... if i use GPU(gpu_layers>0) program just... paused(?).. character name just not generated, but if i set gpu_layers=0, i got result, but slow(
Card: RTX 4070

**Comment by Hukasx0** [comment]
What you are describing is the inability to load the model on the GPU, but it works correctly on the CPU (gpu_layers=0 makes the model load on the CPU).
I do not have a card that supports CUDA, I have a card from AMD, which makes it impossible for me to test this personally. However, after a little research I was able to get to the fact that perhaps in a virtual environment you need to download the Cuda package to Anaconda: https://anaconda.org/nvidia/cuda
e.g. using `conda install -c nvidia cuda` (which is stated on the page)

**Comment by visteras** [comment]
I install `conda install -c nvidia cuda` but this no work:
CPU is load, GPU is load(and VRAM load too), but i don't see result, PC is half-freezeeng :(
I find issue for llama cpp: https://github.com/abetlen/llama-cpp-python/issues/509
But this using CTransformers...?
